# Generated by Django 4.1.7 on 2023-03-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('original_api', models.CharField(choices=[('EONET', 'EONET'), ('ReliefWeb', 'ReliefWeb')], default=None, max_length=30)),
                ('source', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('category', models.CharField(choices=[('COLD_WAVE', 'Cold Wave'), ('COMPLEX_EMERGENCY', 'Complex Emergency'), ('DROUGHT', 'Drought'), ('DUST_HAZE', 'Dust Haze'), ('EARTHQUAKE', 'Earthquake'), ('EPIDEMIC', 'Epidemic'), ('EXTRA_TROPICAL_CYCLONE', 'Extra Tropical Cyclone'), ('FIRE', 'Fire'), ('FLOOD', 'Flood'), ('HEAT_WAVE', 'Heat Wave'), ('INSECT_INFESTATION', 'Insect Infestation'), ('LANDSLIDE', 'Landslide'), ('MUDSLIDE', 'Mudslide'), ('MAN_MADE', 'Man Made'), ('OTHER', 'Other'), ('SEA_LAKE_ICE', 'Sea Lake Ice'), ('SEVERE_STORM', 'Severe Storm'), ('SNOW', 'Snow'), ('TEMPERATURE_EXTREME', 'Temperature Extreme'), ('TROPICAL_CYCLONE', 'Tropical Cyclone'), ('TSUNAMI', 'Tsunami'), ('VOLCANO', 'Volcano'), ('WATER_COLOR', 'Water Color'), ('WILDFIRE', 'Wildfire')], default=None, max_length=25)),
                ('reference', models.CharField(blank=True, max_length=60, null=True)),
                ('country', models.CharField(blank=True, max_length=60, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=1500, null=True)),
                ('status', models.CharField(blank=True, max_length=60, null=True)),
                ('longitudinal', models.FloatField(blank=True, null=True)),
                ('latitudinal', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
