# Generated by Django 4.1.7 on 2023-03-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
